services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env # 環境変数ファイル
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    image: postgres:16
    container_name: MJApp
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55word
      POSTGRES_DB: MJAppDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: Pa55word
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  # pgadmin_data:
